# Generated by Django 2.1.3 on 2018-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
