# Generated by Django 2.1.3 on 2018-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
