# Generated by Django 2.1.3 on 2018-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.DateTimeField()),
                ('content', models.TextField()),
                ('is_disabled', models.BooleanField()),
            ],
        ),
    ]
